In [1]:
import random as rd
import numpy as np

v = []
n = int(input("What is the length of the vector? "))
for i in range(n):
    v.append(3*rd.random())
v = np.array(v)
print(v)

[1.7310893  2.61339536 2.91269745]


In [2]:
a = np.exp(v)*(1+np.sin(2*v))
print(a)

b = np.cos(v)**3+np.sin(v)**3
print(b)

[ 3.86736623  1.76587646 10.27136658]
[ 0.95796668 -0.51633233 -0.91209424]
