In [1]:
import numpy as np
from findPath import *

labyrent1=np.array([[1, 1, 0, 0, 0],[0, 1, 1, 1, 1],[0, 0, 0, 0, 1],[0, 0, 0, 0, 1]])
labyrent2=np.array([[1, 0, 0, 0, 0],[1, 0, 0, 0, 0],[1, 0, 0, 0, 0],[1, 1, 1, 1, 1]])

print(labyrent1)
print(findPath(labyrent1))

[[1 1 0 0 0]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]]
RDRRRDD
